spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanly?useSSL=false
    username: root
    password: mk123654
  thymeleaf:
    cache: true
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        validator:
          apply_to_ddl: false
        show_sql: true

    open-in-view: false
    hibernate:
      ddl-auto: update
  mvc:
    format:
      date-time: iso
    path match:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8082